package:
    name: sls_detector_tools
    version: 0.0.1

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
        - setuptools
        - numpy

    run:
        - python
        - numpy 
        - pyserial
        - pyzmq
        - scipy
        - matplotlib
        - seaborn

test:
      imports:
         - sls_detector_tools


about:
    summary: "Support scripts for analysing detector data"
